### ISSUE TITLE
Not really issue more an off topic

### ISSUE THREAD

**Issue by maxhartung** [RehabMan/Gigabyte-BRIX-s-DSDT-Patch#1]
Hi,

I don't know other method to contact you but I really need some info regarding DSDT patching because I am preety dumb at it. Here is my story:

I extracted using Clover DSDT + other SSDT I patched in DSDT and an SSDT named SSDT-3-SaSsdt Rename GFX0 to IGPU using your patches (I know that it's a laptop patch but it seems good for PCs) and put in the patched folder in Clover. The thing is that I also put Rename GFX0 to IGPU in the Clover to see if there are any remaining patching to be done and it seems like there is. Clover says that is patches something but I don't know where. I searched every SSDT for GFX0 and there are just 2: DSDT and the above SSDT.

The GFX0 device is in the SSDT-3-SaSsdt not in the DSDT seems strange a little bit.

Next, I want to enable Powernap because sleep works just fine my own patched DSDT + Clover patch. 

Can you point me in the right direction for the IGPU patching, powernap and for the XHCI settings needed in the Gigabyte UEFI (Smart Auto, enable, disable,auto)?

Mobo: Gigabyte B85M-D2V with F5 (the latest ones are buggy)
CPU: Intel Core i3 4170 @ 3.7 GHz
RAM: Kingston 8 GB
GPU: Intel HD Graphics 4400
SSD: Samsung 840 EVO 120 GB
OS: macOS 10.13.4

You can find the DSDT and SSDTs here: 

[DSDT and SSDTs.zip](https://github.com/RehabMan/Gigabyte-BRIX-s-DSDT-Patch/files/1713659/DSDT.and.SSDTs.zip)

Thanks a lot !

**Comment by RehabMan** [comment]
It is best to do all renames with config.plist/ACPI/DSDT/Patches, just like I do in this BRIX repo.
Read my hotpatch guide for details:
http://www.tonymacx86.com/threads/guide-using-clover-to-hotpatch-acpi.200137/

As far as USB configuration, read here:
https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/
